version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: ecommerce-frontend-new
    ports:
      - "3000:3000"
    networks:
      - frontend-net
      - backend-net
    depends_on:
      - backend

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  backend:
    build: .
    container_name: ecommerce-backend-new
    ports:
      - "5000:5000" 
    networks:
      - backend-net
    env_file:
      - ./.env
    depends_on:
      - mongo

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  mongo:
    image: mongo:7
    container_name: ecommerce-mongo-2
    ports:
      - "27017:27017"
    volumes:  
      - mongo-data:/data/db
    networks:
      - backend-net

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

networks:
  frontend-net:
    driver: bridge

  backend-net:
    driver: bridge

volumes:
  mongo-data: